# Generated by Django 2.2 on 2019-07-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ems_number', models.CharField(max_length=120)),
                ('ems_name', models.CharField(max_length=120)),
            ],
        ),
    ]
