# Generated by Django 2.2 on 2019-07-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0004_auto_20190710_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('questions', 'Questions'), ('problems', 'Problems'), ('other', 'Other')], default='questions', max_length=50)),
                ('title', models.CharField(max_length=120)),
                ('detail', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
